// Nombres en español de las categorías de Modrinth.

export const CAT_NAMES: Record<string, string> = {
  'adventure':          'Aventura',
  'combat':             'Combate',
  'challenging':        'Desafiante',
  'lightweight':        'Ligero',
  'magic':              'Magia',
  'quests':             'Misiones',
  'multiplayer':        'Multijugador',
  'optimization':       'Optimización',
  'technology':         'Tecnología',
  'miscellaneous':      'Variado',
  'cursed':             'Cursed',
  'decoration':         'Decoración',
  'economy':            'Economía',
  'equipment':          'Equipamiento',
  'food':               'Comida',
  'game-mechanics':     'Mecánicas de juego',
  'library':            'Librería',
  'management':         'Gestión',
  'minigame':           'Minijuego',
  'mobs':               'Mobs',
  'social':             'Social',
  'storage':            'Almacenamiento',
  'transportation':     'Transporte',
  'utility':            'Utilidad',
  'worldgeneration':    'Generación de mundo',
  'world-generation':   'Generación de mundo',
  'modded':             'Moddeado',
  'realistic':          'Realista',
  'simplistic':         'Simplista',
  'themed':             'Temático',
  'tweaks':             'Ajustes',
  'vanilla-like':       'Tipo Vainilla',
  'semi-realistic':     'Semi Realista',
  'fantasy':            'Fantasía',
  'cartoon':            'Cartoon',
  'audio':              'Audio',
  'blocks':             'Bloques',
  'core-shaders':       'Core Shaders',
  'entities':           'Entidades',
  'environment':        'Entorno',
  'fonts':              'Fuentes',
  'gui':                'GUI',
  'items':              'Objetos',
  'locale':             'Idioma',
  'models':             'Modelos',
  'atmosphere':         'Atmósfera',
  'bloom':              'Bloom',
  'colored-lighting':   'Iluminación de color',
  'foliage':            'Follaje',
  'path-tracing':       'Path Tracing',
  'pbr':                'PBR',
  'reflections':        'Reflejos',
  'shadows':            'Sombras',
  '8x':                 '8x o menor',
  '16x':                '16x',
  '32x':                '32x',
  '48x':                '48x',
  '64x':                '64x',
  '128x':               '128x',
  '256x':               '256x',
  '512x':               '512x o mayor',
  '512x-and-above':     '512x o mayor',
  'potato':             'Potato',
  'low':                'Bajo',
  'medium':             'Medio',
  'high':               'Alto',
  'screenshot':         'Screenshot',
  'client':             'Cliente',
  'server':             'Servidor',
}

export function catLabel(name: string): string {
  return CAT_NAMES[name] ?? name
}
